name: dev_deploy_to_aws
on: 
  push:
    branches:
    - dev



jobs:
  dev_eploy_to_aws: 
      if: ${{ github.ref == 'refs/heads/dev' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1
        - name: Copy Data
          run: |
            echo "Hello"
            echo "Deploying to production server on branch $GITHUB_REF"
            ls -la
            aws sync ./glue_pyspark_job  s3://dev-tweets-source-meta/pyspark_script/

