name: dev_deploy_to_aws
on: 
  push:
    branches:
    - dev



jobs:
  dev_eploy_to_aws: 
      if: ${{ github.ref == 'refs/heads/dev' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1
        - name: Copy Data
          run: |
            echo "Hello"
            echo "Copy data to development environment on aws server on branch $GITHUB_REF"
            ls -la
            aws s3 sync ./glue_pyspark_job  s3://dev-tweets-source-meta/pyspark_script/
            cd lambda_tweets_loader
            zip -r ../TweetLoaderZIP.zip .
            cd ../ 
            ls -la
            aws s3 cp TweetLoaderZIP.zip s3://dev-tweets-source-meta/lambda-source/

        - name: Set parameters
          run: |
            aws ssm put-parameter --name current_env --value "dev"  --type "String" --overwrite
            #cd user_ids
            ls -la
            #cat user_ids.txt
            #cd ../
            cat ./user_ids/user_ids.txt
            user_ids=`cat ./user_ids/user_ids.txt`
            aws ssm put-parameter --name UserIDs --value $user_ids  --type "String" --overwrite
            aws ssm put-parameter --name DEV_TWEETS_DATA --value ${{ secrets.DEV_TWEETS_DATA }}  --type "String" --overwrite
            aws ssm put-parameter --name DEV_TWEETS_SOURCE_META --value ${{ secrets.DEV_TWEETS_SOURCE_META }}  --type "String" --overwrite
